import * as mongoose from 'mongoose';

/**
 * Estructura de un documento de tipo player
 */
export interface IPlayer extends mongoose.Document {
  'Name': string,
  'Team': string,
  'Position': string,
  'Overall': number,
  'Outside Scoring': number,
  'Close Shot': number,
  'Mid-Range Shot': number,
  'Three-Point Shot': number,
  'Free Throw': number,
  'Shot IQ': number,
  'Offensive Consistency': number,
  'Athleticism': number,
  'Speed': number,
  'Acceleration': number,
  'Strength': number,
  'Vertical': number,
  'Stamina': number,
  'Hustle': number,
  'Overall Durability': number,
  'Inside Scoring': number,
  'Layup': number,
  'Standing Dunk': number,
  'Driving Dunk': number,
  'Post Hook': number,
  'Post Fade': number,
  'Post Control': number,
  'Draw Foul': number,
  'Hands': number,
  'Playmaking': number,
  'Pass Accuracy': number,
  'Ball Handle': number,
  'Speed with Ball': number,
  'Pass IQ': number,
  'Pass Vision': number,
  'Defending': number,
  'Interior Defense': number,
  'Perimeter Defense': number,
  'Steal': number,
  'Block': number,
  'Lateral Quickness': number,
  'Help Defense IQ': number,
  'Pass Perception': number,
  'Defensive Consistency': number,
  'Rebounding': number,
  'Offensive Rebound': number,
  'Defensive Rebound': number,
  'Intangibles': number,
  'Potential': number,
  'Total Attributes': number,
  'Pertenencia Cluster 0': number,
  'Pertenencia Cluster 1': number,
  'Pertenencia Cluster 2': number,
  'Pertenencia Cluster 3': number,
  'Basketball Reference Player Id': string,
  'Plus/Minus PG Cluster 0': number,
  'Shared Time PG Cluster 0': number,
  'Compatibilidad PG Cluster 0': number,
  'Plus/Minus PG Cluster 1': number,
  'Shared Time PG Cluster 1': number,
  'Compatibilidad PG Cluster 1': number,
  'Plus/Minus PG Cluster 2': number,
  'Shared Time PG Cluster 2': number,
  'Compatibilidad PG Cluster 2': number,
  'Plus/Minus PG Cluster 3': number,
  'Shared Time PG Cluster 3': number,
  'Compatibilidad PG Cluster 3': number,
  'Plus/Minus SG Cluster 0': number,
  'Shared Time SG Cluster 0': number,
  'Compatibilidad SG Cluster 0': number,
  'Plus/Minus SG Cluster 1': number,
  'Shared Time SG Cluster 1': number,
  'Compatibilidad SG Cluster 1': number,
  'Plus/Minus SG Cluster 2': number,
  'Shared Time SG Cluster 2': number,
  'Compatibilidad SG Cluster 2': number,
  'Plus/Minus SG Cluster 3': number,
  'Shared Time SG Cluster 3': number,
  'Compatibilidad SG Cluster 3': number,
  'Plus/Minus SF Cluster 0': number,
  'Shared Time SF Cluster 0': number,
  'Compatibilidad SF Cluster 0': number,
  'Plus/Minus SF Cluster 1': number,
  'Shared Time SF Cluster 1': number,
  'Compatibilidad SF Cluster 1': number,
  'Plus/Minus SF Cluster 2': number,
  'Shared Time SF Cluster 2': number,
  'Compatibilidad SF Cluster 2': number,
  'Plus/Minus SF Cluster 3': number,
  'Shared Time SF Cluster 3': number,
  'Compatibilidad SF Cluster 3': number,
  'Plus/Minus PF Cluster 0': number,
  'Shared Time PF Cluster 0': number,
  'Compatibilidad PF Cluster 0': number,
  'Plus/Minus PF Cluster 1': number,
  'Shared Time PF Cluster 1': number,
  'Compatibilidad PF Cluster 1': number,
  'Plus/Minus PF Cluster 2': number,
  'Shared Time PF Cluster 2': number,
  'Compatibilidad PF Cluster 2': number,
  'Plus/Minus PF Cluster 3': number,
  'Shared Time PF Cluster 3': number,
  'Compatibilidad PF Cluster 3': number,
  'Plus/Minus C Cluster 0': number,
  'Shared Time C Cluster 0': number,
  'Compatibilidad C Cluster 0': number,
  'Plus/Minus C Cluster 1': number,
  'Shared Time C Cluster 1': number,
  'Compatibilidad C Cluster 1': number,
  'Plus/Minus C Cluster 2': number,
  'Shared Time C Cluster 2': number,
  'Compatibilidad C Cluster 2': number,
  'Plus/Minus C Cluster 3': number,
  'Shared Time C Cluster 3': number,
  'Compatibilidad C Cluster 3': number,
  'ImgUrl': string,
}
/**
 * Esquema de la entidad player en base de datos
 */
const PlayerSchema: mongoose.Schema = new mongoose.Schema({
  'Name': { type: String, required: true, unique: true },
  'Team': { type: String, required: true },
  'Position': { type: String, required: true },
  'Overall': { type: Number },
  'Outside Scoring': { type: Number },
  'Close Shot': { type: Number },
  'Mid-Range Shot': { type: Number },
  'Three-Point Shot': { type: Number },
  'Free Throw': { type: Number },
  'Shot IQ': { type: Number },
  'Offensive Consistency': { type: Number },
  'Athleticism': { type: Number },
  'Speed': { type: Number },
  'Acceleration': { type: Number },
  'Strength': { type: Number },
  'Vertical': { type: Number },
  'Stamina': { type: Number },
  'Hustle': { type: Number },
  'Overall Durability': { type: Number },
  'Inside Scoring': { type: Number },
  'Layup': { type: Number },
  'Standing Dunk': { type: Number },
  'Driving Dunk': { type: Number },
  'Post Hook': { type: Number },
  'Post Fade': { type: Number },
  'Post Control': { type: Number },
  'Draw Foul': { type: Number },
  'Hands': { type: Number },
  'Playmaking': { type: Number },
  'Pass Accuracy': { type: Number },
  'Ball Handle': { type: Number },
  'Speed with Ball': { type: Number },
  'Pass IQ': { type: Number },
  'Pass Vision': { type: Number },
  'Defending': { type: Number },
  'Interior Defense': { type: Number },
  'Perimeter Defense': { type: Number },
  'Steal': { type: Number },
  'Block': { type: Number },
  'Lateral Quickness': { type: Number },
  'Help Defense IQ': { type: Number },
  'Pass Perception': { type: Number },
  'Defensive Consistency': { type: Number },
  'Rebounding': { type: Number },
  'Offensive Rebound': { type: Number },
  'Defensive Rebound': { type: Number },
  'Intangibles': { type: Number },
  'Potential': { type: Number },
  'Total Attributes': { type: Number },
  'Pertenencia Cluster 0': { type: Number },
  'Pertenencia Cluster 1': { type: Number },
  'Pertenencia Cluster 2': { type: Number },
  'Pertenencia Cluster 3': { type: Number },
  'Basketball Reference Player Id': { type: String, required: true },
  'Plus/Minus PG Cluster 0': { type: Number },
  'Shared Time PG Cluster 0': { type: Number },
  'Compatibilidad PG Cluster 0': { type: Number },
  'Plus/Minus PG Cluster 1': { type: Number },
  'Shared Time PG Cluster 1': { type: Number },
  'Compatibilidad PG Cluster 1': { type: Number },
  'Plus/Minus PG Cluster 2': { type: Number },
  'Shared Time PG Cluster 2': { type: Number },
  'Compatibilidad PG Cluster 2': { type: Number },
  'Plus/Minus PG Cluster 3': { type: Number },
  'Shared Time PG Cluster 3': { type: Number },
  'Compatibilidad PG Cluster 3': { type: Number },
  'Plus/Minus SG Cluster 0': { type: Number },
  'Shared Time SG Cluster 0': { type: Number },
  'Compatibilidad SG Cluster 0': { type: Number },
  'Plus/Minus SG Cluster 1': { type: Number },
  'Shared Time SG Cluster 1': { type: Number },
  'Compatibilidad SG Cluster 1': { type: Number },
  'Plus/Minus SG Cluster 2': { type: Number },
  'Shared Time SG Cluster 2': { type: Number },
  'Compatibilidad SG Cluster 2': { type: Number },
  'Plus/Minus SG Cluster 3': { type: Number },
  'Shared Time SG Cluster 3': { type: Number },
  'Compatibilidad SG Cluster 3': { type: Number },
  'Plus/Minus SF Cluster 0': { type: Number },
  'Shared Time SF Cluster 0': { type: Number },
  'Compatibilidad SF Cluster 0': { type: Number },
  'Plus/Minus SF Cluster 1': { type: Number },
  'Shared Time SF Cluster 1': { type: Number },
  'Compatibilidad SF Cluster 1': { type: Number },
  'Plus/Minus SF Cluster 2': { type: Number },
  'Shared Time SF Cluster 2': { type: Number },
  'Compatibilidad SF Cluster 2': { type: Number },
  'Plus/Minus SF Cluster 3': { type: Number },
  'Shared Time SF Cluster 3': { type: Number },
  'Compatibilidad SF Cluster 3': { type: Number },
  'Plus/Minus PF Cluster 0': { type: Number },
  'Shared Time PF Cluster 0': { type: Number },
  'Compatibilidad PF Cluster 0': { type: Number },
  'Plus/Minus PF Cluster 1': { type: Number },
  'Shared Time PF Cluster 1': { type: Number },
  'Compatibilidad PF Cluster 1': { type: Number },
  'Plus/Minus PF Cluster 2': { type: Number },
  'Shared Time PF Cluster 2': { type: Number },
  'Compatibilidad PF Cluster 2': { type: Number },
  'Plus/Minus PF Cluster 3': { type: Number },
  'Shared Time PF Cluster 3': { type: Number },
  'Compatibilidad PF Cluster 3': { type: Number },
  'Plus/Minus C Cluster 0': { type: Number },
  'Shared Time C Cluster 0': { type: Number },
  'Compatibilidad C Cluster 0': { type: Number },
  'Plus/Minus C Cluster 1': { type: Number },
  'Shared Time C Cluster 1': { type: Number },
  'Compatibilidad C Cluster 1': { type: Number },
  'Plus/Minus C Cluster 2': { type: Number },
  'Shared Time C Cluster 2': { type: Number },
  'Compatibilidad C Cluster 2': { type: Number },
  'Plus/Minus C Cluster 3': { type: Number },
  'Shared Time C Cluster 3': { type: Number },
  'Compatibilidad C Cluster 3': { type: Number },
  'ImgUrl': { type: String },
});


/**
 * Modelo para un jugador que se recomienda como compañero de otro
 */
 export interface IPlayerRecomendado extends IPlayer {
   Score: number
 }

// Exportar el modelo Player (se aplica el esquema PlayerSchema sobre la interfaz IPlayer)
const Player = mongoose.model<IPlayer>('Player', PlayerSchema, 'players');
export { Player };
